M48
; DRILL file {KiCad 8.0.2} date 2024-06-01T19:49:29+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-01T19:49:29+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.1773Y-2.839
X3.1773Y-3.0665
T2
X3.0709Y-2.0866
X3.0709Y-3.8189
X4.8031Y-2.0866
X4.8031Y-3.8189
M30
