name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome.yaml
      name: Endo Lighing Controller
